#!/usr/bin/env zsh

setopt ERR_EXIT
setopt LOCAL_OPTIONS
setopt NO_UNSET
setopt PIPE_FAIL

function main()
{
  local root=${${(%):-%x}:A:h:h}

  cd $root
  sudo rmmod dmx_usb
  exec sudo insmod dmx_usb.ko
}

main $@
